language: R
sudo: false
cache: packages
warnings_are_errors: true

os:
  - linux
  - osx

r:
  - oldrel
  - release
  - devel
  
jobs:
  exclude:
  - os: osx
    r: devel

before-script:
- R -e "install.packages (c ('roxygen2', 'dbplyr')); roxygen2::roxygenize ('.')"

after-success:
- Rscript -e "covr::codecov()"
